# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbRlHFPzAasTdTuhNQR_3f1Q7DdpQ9QN
"""

goots= ["эклер со сгущенкой" , "эклер с клубникой","эклер пустой" ]
shops = ["Ашан","Перекрёсток","Лента"]
posts = []
for goos in goots:
  goots_posts = []
  for shop in shops:
    prise = int(input(f"Введите цену на товар {goos} в магазине {shop}\n"))
    goots_posts.append(prise)
  posts.append(goots_posts)
bascet = []
for count , value in enumerate(shops):
  total = 0
  for idx , prodact in enumerate(goots):
    total+= posts[idx][count]
  print(f"стоимость корзины в магазине {value}: {total}")
  bascet.append(total)
min_dx = 0
min_value = None
for idx , value in enumerate(bascet):
  if min_value == None  or value < min_value:
    min_dx = idx
    min_value = value
print(f"минимальная цена в магазине {shops[min_dx]}")

